spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jwt
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect

logging:
    level:
     org.spring.framework.security: TRACE
